### ISSUE TITLE
v1.0.6-testnet: constraint #1685 is not satisfied

### ISSUE THREAD

**Issue by dferendo** [succinctlabs/sp1#933]
Upgrading to [v1.0.6-testnet](https://github.com/succinctlabs/sp1/releases/tag/v1.0.6-testnet) gives the following error when generating `prove_plonk` proofs. [v1.0.4-testnet](https://github.com/succinctlabs/sp1/releases/tag/v1.0.4-testnet) works fine, tested on an 8 cores 128gb RAM machine:

```
TRAP encountered. No backtrace available
TRAP encountered. No backtrace available
TRAP encountered. No backtrace available
TRAP encountered. No backtrace available
[sp1] building plonk bn254 artifacts in development mode
13:10:03 INF compiling circuit
13:10:03 INF parsed circuit inputs nbPublic=2 nbSecret=4292
13:10:08 INF building constraint builder nbConstraints=7426273
13:10:08 DBG fetching SRS from mem cache curve=bn254 key=kzgsrs-bn254-8388611 package=kzgsrs size=8388611
13:10:08 DBG SRS not found in mem cache curve=bn254 package=kzgsrs size=8388611
13:10:08 DBG SRS not found in cache, generating curve=bn254 package=kzgsrs size=8388611
13:13:33 ERR error="constraint #1685 is not satisfied: qL⋅xa + qR⋅xb + qO⋅xc + qM⋅(xaxb) + qC != 0 → 0 + 0 + 0 + 0 + -1 != 0" nbConstraints=7426273
panic: constraint #1685 is not satisfied: qL⋅xa + qR⋅xb + qO⋅xc + qM⋅(xaxb) + qC != 0 → 0 + 0 + 0 + 0 + -1 != 0

goroutine 17 [running, locked to thread]:
github.com/succinctlabs/sp1-recursion-gnark/sp1.Build({0x140001cf140, 0x34})
        /Users/dferendo-simply/.cargo/git/checkouts/sp1-20c98843a1ffc860/1049583/recursion/gnark-ffi/go/sp1/build.go:146 +0xcf4
main.BuildPlonkBn254(0x14000078e01?)
        /Users/dferendo-simply/.cargo/git/checkouts/sp1-20c98843a1ffc860/1049583/recursion/gnark-ffi/go/main.go:58 +0x24
[1]    40636 abort      cargo run --bin operator --release

```

**Comment by ratankaliani** [comment]
`v1.0.6-testnet` was a broken release that has now been yanked, sorry about that! Resolving, as `v1.0.7-testnet` has been released.
